mysite/urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

import boards.views as boards_views
import notifications.views as notifications_views
import search.views as search_views
import subjects.views as subjects_views
import users.views as users_views
from subjects.sitemaps import SubjectSitemap
from messenger.urls import *

sitemaps = {
    'subjects': SubjectSitemap,
}

urlpatterns = [
    

    re_path(r'^home/$',login_required(subjects_views.HomePageView.as_view()), name='home'),
    re_path(r'^$',users_views.user_login,name='login'),
    re_path(r'^s/(?P<board>[-\w]+)/(?P<subject>[-\w]+)/$',
        subjects_views.subject_detail,
        name='subject_detail'),
    re_path(r'^b/$',boards_views.BoardsPageView.as_view(), name='view_all_boards'),
    re_path(r'^b/(?P<board>[-\w]+)/$',
        boards_views.BoardPageView.as_view(),
        name='board'),
    
    re_path(r'^b/(?P<board>[-\w]+)/edit_board_cover/$',
        boards_views.edit_board_cover,
        name='edit_board_cover'),
    re_path(r'^b/(?P<board>[-\w]+)/subscription/$',
        boards_views.subscribe,
        name='subscribe'),
    re_path(r'^b/(?P<subject>[-\w]+)/like/$',
        subjects_views.like_subject,
        name='like'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/subscriptions/$', boards_views.UserSubscriptionListView.as_view(),
        name='user_subscription_list'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/boards/$', boards_views.UserCreatedBoardsPageView.as_view(),
        name='user_created_boards'),
    re_path(r'^new_post/$',subjects_views.new_subject, name='new_subject'),
    re_path(r'^edit_subject/(?P<subject>[-\w]+)/$', subjects_views.edit_subject, name='edit_subject'),
    re_path(r'^new_board/$',boards_views.new_board, name='new_board'),

    # user profiles
    re_path(r'^u/$', users_views.UsersPageView.as_view(), name='view_all_users'),
    re_path(r'^u/following/$', users_views.FollowingPageView.as_view(), name='view_following'),
    re_path(r'^u/followers/$', users_views.FollowersPageView.as_view(), name='view_all_followers'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/$', users_views.UserProfilePageView.as_view(), name='user_profile'),
    re_path(r'^u/follow_user/(?P<user_id>\d+)/$',
        users_views.follow_user,
        name='follow_user'),
    re_path(r'^u/send_message_request/(?P<user_id>\d+)/$',
        users_views.send_message_request,
        name='send_message_request'),
    re_path(r'^u/accept_message_request/(?P<user_id>\d+)/$',
        users_views.accept_message_request,
        name='accept_message_request'),
    re_path(r'^u/friends/all/$', users_views.all_friends, name='all_friends'),
    re_path(r'^u/friends/requests/$', users_views.all_message_requests, name='all_message_requests'),
    re_path(r'^activities/$', notifications_views.ActivitiesPageView.as_view(), name='activities'),
    re_path(r'^activities/check/$', notifications_views.check_activities, name='check_activities'),

    # login / logout urls
    re_path(r'^login/$',users_views.user_login,name='login'),
    re_path(r'^logout/$',users_views.user_logout,
            name='logout'),
    re_path(r'^logout-then-login/$',
            auth_views.logout_then_login,
            name='logout_then_login'),

    # password change re_paths
    re_path(r'^password_change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    re_path(r'^password-change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),


    # user registration
    re_path(r'^signup/$',
        users_views.register_user,
        name='signup'),

    # verify username availability in database via ajax request
    re_path(r'^signup/check_username/$', users_views.check_username, name='check_username'),

    # profile edit
    re_path(r'^profile_edit/$', users_views.profile_edit,
        name='profile_edit'),
    re_path(r'^picture_change/$', users_views.change_picture,
        name='picture_change'),

    # search
    re_path(r'^search/$',search_views.search, name='search'),
    re_path(r'^board_search/(?P<board_slug>[-\w]+)/$',search_views.search, name='board_search'),

    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    
    re_path(r'^messages/', include('messenger.urls')),

    path('', include('pwa.urls'))

]

if True:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

boards/models.py
from datetime import timedelta

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.db import models
from django.db.models.signals import m2m_changed
from django.utils import timezone

from slugify import UniqueSlugify


class Board(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, null=True, blank=True)
    description = models.TextField(max_length=500)
    cover = models.ImageField(upload_to='board_covers/', blank=True, null=True)
    admins = models.ManyToManyField(User, related_name='inspected_boards')
    subscribers = models.ManyToManyField(User, related_name='subscribed_boards')
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        """Unicode representation for a board model."""
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = board_slugify(f"{self.title}")

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Return absolute url for a board."""
        return reverse('board',
                       args=[self.slug])

    def get_admins(self):
        """Return admins of a board."""
        return self.admins.all()

    def get_picture(self):
        """Return cover url (if any) of a board."""
        default_picture = settings.STATIC_URL + 'img/cover.png'
        if self.cover:
            return self.cover.url
        else:
            return default_picture



def admins_changed(sender, **kwargs):
    if kwargs['instance'].admins.count() > 3:
        raise ValidationError("You can't assign more than three admins.")
m2m_changed.connect(admins_changed, sender=Board.admins.through)  # noqa: E305


def board_unique_check(text, uids):
    if text in uids:
        return False
    return not Board.objects.filter(slug=text).exists()


board_slugify = UniqueSlugify(
                    unique_check=board_unique_check,
                    to_lower=True,
                    max_length=80,
                    separator='_',
                    capitalize=False
                )

boards/forms.py
from django import forms

from .models import Board


class BoardForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}))
    cover = forms.ImageField(
        widget=forms.FileInput(),
        required=False
    )

    class Meta:
        model = Board
        fields = ('title', 'description', 'cover')

boards/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import ListView

import requests
from PIL import Image

from mysite.decorators import ajax_required
from subjects.models import Subject
from utils import check_image_extension

from .decorators import user_is_board_admin
from .forms import BoardForm
from .models import Board


class BoardsPageView(ListView):
    model = Board
    queryset = Board.objects.all()
    paginate_by = 20
    template_name = 'boards/view_all_boards.html'
    context_object_name = 'boards'


class BoardPageView(ListView):
    model = Subject
    paginate_by = 20
    template_name = 'boards/board.html'
    context_object_name = 'subjects'

    def get_queryset(self, **kwargs):
        self.board = get_object_or_404(Board,
                                       slug=self.kwargs['board'])
        return self.board.submitted_subjects.filter(active=True)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["bv"] = True
        context["admins"] = self.board.admins.all()
        context["board"] = self.board
        return context


class UserSubscriptionListView(LoginRequiredMixin, ListView):
    model = Board
    paginate_by = 10
    template_name = 'boards/user_subscription_list.html'
    context_object_name = 'subscriptions'

    def get_queryset(self, **kwargs):
        user = get_object_or_404(User,
                                 username=self.request.user)
        return user.subscribed_boards.all()


@login_required
@ajax_required
def subscribe(request, board):
    board = get_object_or_404(Board,
                              slug=board)
    user = request.user
    if board in user.subscribed_boards.all():
        board.subscribers.remove(user)
    else:
        board.subscribers.add(user)
    return HttpResponse(board.subscribers.count())


class UserCreatedBoardsPageView(LoginRequiredMixin, ListView):
    model = Board
    paginate_by = 20
    template_name = 'boards/user_created_boards.html'
    context_object_name = 'user_boards'

    def get_queryset(self, **kwargs):
        user = get_object_or_404(User,
                                 username=self.request.user)
        return user.inspected_boards.all()


@login_required
def new_board(request):
    board_form = BoardForm()

    if request.method == 'POST':
        board_form = BoardForm(request.POST, request.FILES)
        if board_form.is_valid():
            new_board = board_form.save()
            new_board.admins.add(request.user)
            new_board.subscribers.add(request.user)
            return redirect(new_board.get_absolute_url())
            
    form_filling = True

    return render(request, 'boards/new_board.html', {
        'board_form': board_form, 'form_filling': form_filling
    })


@login_required
@user_is_board_admin
def edit_board_cover(request, board):
    board = get_object_or_404(Board,
                              slug=board)
    if request.method == 'POST':
        board_cover = request.FILES.get('cover')
        if check_image_extension(board_cover.name):
            board.cover = board_cover
            board.save()
            return redirect('board', board=board.slug)
        else:
            return HttpResponse('Filetype not supported. Supported filetypes are .jpg, .png etc.')
    else:
        form_filling = True
        return render(request, 'boards/edit_board_cover.html', {
            'board': board, 'form_filling': form_filling
        })

boards/templates/boards/board.html
{% extends "base_home.html" %}

{% block title %}<title>{{ board.title }} | Elixio</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text=board.title|upper %}
{% if subjects %}
  {% include "includes/partial_subject.html" with subjects=subjects %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Subjects Found</b></h6>
    <div style="margin:0 auto;">
    <p class="text-muted">Be the first one to post a subject in this board.</p>
    </div>
  </div>
{% endif %}

{% endblock %}

boards/templates/boards/edit_board_cover.html
{% extends "base_form.html" %}
{% load crispy_forms_tags %}
{% block title %}<title>Change Your Board Cover | Elixio</title>{% endblock %}


{% block form_content %}

{% include "includes/page_heading.html" with text="Change Your Board Cover" %}
{% if board_form.errors %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{board_form.errors}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endif %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_cover">Cover photo</label>
    <input type="file" class="form-control-file" id="id_cover" name="cover" accept="image/*">
  </div>
   <button type="submit" class="btn btn-primary btn-block" id="submit_cover">Submit</button>
</form>


<script type="text/javascript">
// Check file size
$(document).ready(function(){
  $("input#id_cover").on("change", function () {
    var file_size = this.files[0].size;
    if (file_size > 2097152) {
      alert("Image size should be less than 2 megabytes.")
      $("button#submit_cover").prop('disabled', true);
    } else {
        $("button#submit_cover").prop('disabled', false);
    }
  });
});
</script>

{% endblock %}

boards/templates/boards/new_board.html
{% extends "base_form.html" %}
{% load crispy_forms_tags %}

{% block title %}<title>Create Board | Elixio</title>{% endblock %}

{% block form_content %}
{% include "includes/page_heading.html" with text="Create Board" %}

<form action="{% url 'new_board' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ board_form|crispy }}
 <button type="submit" class="btn btn-success btn-block" style="background-color: #ff4500;">Submit</button>
</form>
<br>
{% endblock %}

boards/templates/boards/user_created_boards.html
{% extends "base_home.html" %}

{% block title %}<title>Your boards | Elixio</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Your Boards" %}
{% if user_boards %}
  {% include "includes/partial_board.html" with boards=user_boards %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Boards Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">You have not created any boards created yet.</p>
    </div>
  </div>
{% endif %}

<script type="text/javascript">
// Subscribe boards
$(document).ready(function(){
  $("a#subscribe_board").on("click", function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $msg=$(this);
    var $subscribe_url=$(this).attr("href");
    var $board_subscribers=$('span#board_subscribers')
    $.ajax({
      url: $subscribe_url,
      type: 'GET',
      success: function (data) {
        if ($msg.text() == 'Subscribe') {
          $msg.removeClass('btn-primary');
          $msg.addClass('btn-secondary');
          $msg.text('Unsubscribe');
          $board_subscribers.text(data + ' readers');
        } else if ($msg.text() == 'Unsubscribe') {
          $msg.removeClass('btn-secondary');
          $msg.addClass('btn-primary');
          $msg.text('Subscribe');
          $board_subscribers.text(data + ' readers');
        } else { console.log('Unexpected error!'); }
      }
    });
    {% endif %}
    return false;
  });
});
</script>

{% endblock %}

boards/templates/boards/user_subscription_list.html
{% extends "base_home.html" %}

{% block title %}<title>Subscription List | Elixio</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Subscription List" %}
<div class="alert alert-light text-center" style="background-color: #0e0e0e; border-color: #000000; color: white; border-radius: 5px;" role="alert">
  Subscribe interesting boards to populate your home feed with interesting subjects.
</div>
{% if subscriptions %}
  {% include "includes/partial_board.html" with boards=subscriptions %}
{% else %}
  <div class="card p-4 my-4 mx-0" style="background-color: #0e0e0e; border-color: #000000; border-radius: 5px;">
    <h6 class="text-center">No Subscriptions Found</h6> 
    <div style="margin:0 auto;">
    <p class="text-muted">You have not subscribed any boards yet.</p>
    </div>
  </div>
{% endif %}

{% endblock %}

boards/templates/boards/view_all_boards.html
{% extends "base_home.html" %}
{% block title %}<title>Subscribe Boards | Elixio</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Subscribe Boards" %}
<div class="alert alert-light text-center" role="alert" style="background-color: #000000;">
  Click the <span class="font-weight-bold">Subscribe</span> button to populate your home feed with interesting board's subjects.
</div>
{% if boards %}
  {% include "includes/partial_board.html" with boards=boards %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Boards Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">There are no boards created yet.</p>
    </div>
  </div>
{% endif %}

{% endblock %}