mysite/urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

import boards.views as boards_views
import notifications.views as notifications_views
import search.views as search_views
import subjects.views as subjects_views
import users.views as users_views
from subjects.sitemaps import SubjectSitemap
from messenger.urls import *

sitemaps = {
    'subjects': SubjectSitemap,
}

urlpatterns = [
    

    re_path(r'^home/$',login_required(subjects_views.HomePageView.as_view()), name='home'),
    re_path(r'^$',users_views.user_login,name='login'),
    re_path(r'^s/(?P<board>[-\w]+)/(?P<subject>[-\w]+)/$',
        subjects_views.subject_detail,
        name='subject_detail'),
    re_path(r'^b/$',boards_views.BoardsPageView.as_view(), name='view_all_boards'),
    re_path(r'^b/(?P<board>[-\w]+)/$',
        boards_views.BoardPageView.as_view(),
        name='board'),
    
    re_path(r'^b/(?P<board>[-\w]+)/edit_board_cover/$',
        boards_views.edit_board_cover,
        name='edit_board_cover'),
    re_path(r'^b/(?P<board>[-\w]+)/subscription/$',
        boards_views.subscribe,
        name='subscribe'),
    re_path(r'^b/(?P<subject>[-\w]+)/like/$',
        subjects_views.like_subject,
        name='like'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/subscriptions/$', boards_views.UserSubscriptionListView.as_view(),
        name='user_subscription_list'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/boards/$', boards_views.UserCreatedBoardsPageView.as_view(),
        name='user_created_boards'),
    re_path(r'^new_post/$',subjects_views.new_subject, name='new_subject'),
    re_path(r'^edit_subject/(?P<subject>[-\w]+)/$', subjects_views.edit_subject, name='edit_subject'),
    re_path(r'^new_board/$',boards_views.new_board, name='new_board'),

    # user profiles
    re_path(r'^u/$', users_views.UsersPageView.as_view(), name='view_all_users'),
    re_path(r'^u/following/$', users_views.FollowingPageView.as_view(), name='view_following'),
    re_path(r'^u/followers/$', users_views.FollowersPageView.as_view(), name='view_all_followers'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/$', users_views.UserProfilePageView.as_view(), name='user_profile'),
    re_path(r'^u/follow_user/(?P<user_id>\d+)/$',
        users_views.follow_user,
        name='follow_user'),
    re_path(r'^u/send_message_request/(?P<user_id>\d+)/$',
        users_views.send_message_request,
        name='send_message_request'),
    re_path(r'^u/accept_message_request/(?P<user_id>\d+)/$',
        users_views.accept_message_request,
        name='accept_message_request'),
    re_path(r'^u/friends/all/$', users_views.all_friends, name='all_friends'),
    re_path(r'^u/friends/requests/$', users_views.all_message_requests, name='all_message_requests'),
    re_path(r'^activities/$', notifications_views.ActivitiesPageView.as_view(), name='activities'),
    re_path(r'^activities/check/$', notifications_views.check_activities, name='check_activities'),

    # login / logout urls
    re_path(r'^login/$',users_views.user_login,name='login'),
    re_path(r'^logout/$',users_views.user_logout,
            name='logout'),
    re_path(r'^logout-then-login/$',
            auth_views.logout_then_login,
            name='logout_then_login'),

    # password change re_paths
    re_path(r'^password_change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    re_path(r'^password-change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),


    # user registration
    re_path(r'^signup/$',
        users_views.register_user,
        name='signup'),

    # verify username availability in database via ajax request
    re_path(r'^signup/check_username/$', users_views.check_username, name='check_username'),

    # profile edit
    re_path(r'^profile_edit/$', users_views.profile_edit,
        name='profile_edit'),
    re_path(r'^picture_change/$', users_views.change_picture,
        name='picture_change'),

    # search
    re_path(r'^search/$',search_views.search, name='search'),
    re_path(r'^board_search/(?P<board_slug>[-\w]+)/$',search_views.search, name='board_search'),

    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    
    re_path(r'^messages/', include('messenger.urls')),

    path('', include('pwa.urls'))

]

if True:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

subjects/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models
from django.utils import timezone
from django.utils.html import escape

import bleach
from slugify import UniqueSlugify

from boards.models import Board


class Subject(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, null=True, blank=True)
    body = models.TextField(max_length=5000, blank=True, null=True)
    photo = models.ImageField(upload_to='subject_photos/', verbose_name=u"Add image (optional)",blank=True, null=True)
    author = models.ForeignKey(User, related_name='posted_subjects', on_delete=models.CASCADE)
    board = models.ForeignKey(Board, related_name='submitted_subjects', on_delete=models.CASCADE)
    points = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_subjects', blank=True)
    mentioned = models.ManyToManyField(User, related_name='m_in_subjects', blank=True)
    rank_score = models.FloatField(default=0.0)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = subject_slugify(f"{self.title}")

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        
        return reverse('subject_detail',
                       args=[self.board.slug,
                             self.slug])

    @staticmethod
    def get_subjects(user=None):
        """Returns a list of subjects."""
        if user:
            subjects = Subject.objects.filter(active=True,author=user)
        else:
            subjects = Subject.objects.filter(active=True)
        return subjects

    @staticmethod
    def search_subjects(query, board=None):
        """Searches for subjects."""
        if board:
            search_results = Subject.objects.filter(active=True,title__icontains=query,board=board)
        else:
            search_results = Subject.objects.filter(active=True,title__icontains=query)
        return search_results

    def get_points(self):
        """Returns number of stars."""
        return self.points.count()

    def linkfy_subject(self):
        """Linkifies the subject body."""
        return bleach.linkify(escape(self.body))

    def set_rank(self):
        """Calculates the rank score of a subject."""
        GRAVITY = 1.2
        time_delta = timezone.now() - self.created
        subject_hour_age = time_delta.total_seconds()
        subject_points = self.points.count() - 1
        self.rank_score = subject_points / pow((subject_hour_age + 2), GRAVITY)
        self.save()


def subject_unique_check(text, uids):
    if text in uids:
        return False
    return not Subject.objects.filter(slug=text).exists()


subject_slugify = UniqueSlugify(
                    unique_check=subject_unique_check,
                    to_lower=True,
                    max_length=80,
                    separator='_',
                    capitalize=False
                )

subjects/forms.py
from django import forms

from boards.models import Board

from .models import Subject


class SubjectForm(forms.ModelForm):
    """
    Form that handles subject data.
    """
    def get_subscribed_boards(self):
        """Return a list of user's subscribed boards."""
        return self.user.subscribed_boards

   
    body = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), required=False)
    board = forms.ModelChoiceField(queryset=Board.objects.all())

    def __init__(self, *args, **kwargs):
        """
        Initialize the form by populating board options with
        user's subscribed boards.
        """
        user = kwargs.pop('user', None)
        super(SubjectForm, self).__init__(*args, **kwargs)
        if user is not None:
            subscribed_boards = user.subscribed_boards.all()
            self.fields['board'].queryset = subscribed_boards
            if not subscribed_boards:
                self.fields['board'].help_text = "You need to <b>subscribe</b> a board to post in it."

    class Meta:
        model = Subject
        fields = ('title', 'body', 'photo', 'board')

subjects/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import OperationalError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.views.generic import ListView

import requests
from django.http import HttpResponseRedirect
from mysite.decorators import ajax_required
from notifications.models import Notification
from utils import image_compression

from .decorators import user_is_subject_author
from .forms import SubjectForm
from .models import Subject




def get_home_subjects():
    try:
        home_subjects = Subject.get_subjects()
    except OperationalError:
        home_subjects = None
    return home_subjects


class HomePageView(ListView):
    model = Subject
    queryset = get_home_subjects()
    paginate_by = 15
    template_name = 'subjects/home.html'
    context_object_name = 'subjects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context



def subject_detail(request, board, subject):
    """
    Displays the subject details and handles comment action.
    """
    subject = get_object_or_404(Subject,
                                board__slug=board,
                                slug=subject)
    board = subject.board
    bv = True
    user = request.user
    admins = board.admins.all()


    return render(request, 'subjects/subject.html', {
        'subject': subject,
        'board': board,
        'bv': bv,
        'admins': admins
    })


@login_required
def new_subject(request):
    """
    Displays a form & handle action for creating new subject.
    """
    subject_form = SubjectForm(**{'user': request.user})

    if request.method == 'POST':
        subject_form = SubjectForm(request.POST, request.FILES)
        if subject_form.is_valid():
            new_subject = subject_form.save(commit=False)
            author = request.user
            new_subject.author = author
            new_subject.save()
            new_subject.points.add(author)
            new_subject.save()
            if new_subject.photo:
                image_compression(new_subject.photo.name)

            return HttpResponseRedirect('/u/%s/' % new_subject.author)

    form_filling = True

    return render(request, 'subjects/new_subject.html', {
        'subject_form': subject_form, 'form_filling': form_filling
    })


@login_required
@ajax_required
def like_subject(request, subject):
    """
    Ajax call to like a subject & return status.
    """
    data = dict()
    subject = get_object_or_404(Subject,
                                slug=subject)
    user = request.user
    if subject in user.liked_subjects.all():
        subject.points.remove(user)
        data['is_starred'] = False
    else:
        subject.points.add(user)
        data['is_starred'] = True

    data['total_points'] = subject.points.count()
    return JsonResponse(data)



@login_required
@user_is_subject_author
def edit_subject(request, subject):
    """
    Displays edit form for subjects and handles edit action.
    """
    subject = get_object_or_404(Subject,
                                slug=subject)
    if request.method == 'POST':
        subject_form = SubjectForm(instance=subject,
                                   data=request.POST,
                                   files=request.FILES)
        if subject_form.is_valid():
            subject_form.save()
            return redirect(subject.get_absolute_url())
        else:
            subject_form = SubjectForm(instance=subject)
    else:
        subject_form = SubjectForm(instance=subject)

    form_filling = True

    return render(request, 'subjects/edit_subject.html', {
        'subject_form': subject_form, 'form_filling': form_filling
    })

subjects/templates/subjects/base.html
{% extends "base_form.html" %}
{% block content %}
<div class="container mx-auto my-4 form_content_block">
    <div class="row">
      <div class="container mx-auto" style="width: 50%;">
        {% block form_content %}
        {% endblock %}
      </div>
    </div>
  </div>
{% endblock %}  

subjects/templates/subjects/edit_subject.html
{% extends "base_form.html" %}
{% load crispy_forms_tags %}
{% block title %}<title>Edit Subject | Elixio</title>{% endblock %}

{% block form_content %}

{% include "includes/page_heading.html" with text="Edit Subject" %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ subject_form|crispy }}

  <button type="submit" class="btn btn-primary btn-block" id="submit_subject">Submit</button>
</form>

<script type="text/javascript">
// Check file size
$(document).ready(function(){
  $("#id_photo").on("change", function () {
    var file_size = this.files[0].size;
    if (file_size > 2097152) {
      alert("Image size should be less than 2 megabytes.");
      $("button#submit_subject").prop('disabled', true);
    } else {
      $("button#submit_subject").prop('disabled', false);
    }
  });
});
</script>

{% endblock %}

subjects/templates/subjects/home.html
{% extends "base_home.html" %}

{% block content %}
{% if request.user.is_authenticated %}
{% include "includes/page_heading.html" with text="Homepage" %}
{% include "includes/partial_subject.html" with subjects=subjects %}
{%endif%}
{% endblock content %}

subjects/templates/subjects/new_subject.html
{% extends "base_form.html" %}
{% load crispy_forms_tags %}

{% block title %}<title>Create New Post | Elixio</title>{% endblock %}

{% block form_content %}
{% include "includes/page_heading.html" with text="Create Post" %}

<form action="{% url 'new_subject' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ subject_form|crispy }}
  <button type="submit" class="btn btn-primary btn-block" style="background-color: #ff4500;">Submit</button>
  <br>
</form>
{% endblock %}

subjects/templates/subjects/subject.html
{% extends "base_home.html" %}
{% load boards_tags %}
{% load humanize %}
{% load emoticons_tags %}
{% load static %}

{% block title %}<title>{{ subject.title }} | Elixio</title>{% endblock %}

{% block meta_description %}{{ subject.body }}{% endblock %}

{% block content %}
<style>
  </style>
    .card-styling { margin-bottom:10px; }
    .card-body-styling { padding:10px; }
    .star-partition { float:left; width:10%; text-align:center; padding-top:10px; }
    .body-partition { float:right; width:90%; }
    .card-photo-stlying { text-align:center; padding:5px; }
    .card-bottom-area { padding-top:10px; font-weight:600; font-size:12px; }
    .card-bottom-area a { text-decoration:none; }
    i#star_icon.fa-lg { font-size:1.6em; }
    span#js-star-count { font-weight:600; }
    .board-link { text-decoration:none; font-weight:600; }
    .profile-link { text-decoration:none; }
    .post-info { font-size:11px; }
<div class="card card-styling mt-4" style="border:0;">
  <div class="card-body card-body-styling">

    <div class="star-partition">
      <a 
         style="text-decoration:none;"
         title="{{ subject.points.count }} points"
         id="js-star-subject">

         {% if subject in user.liked_subjects.all %}
           <i class="fa fa-star fa-lg" aria-hidden="true" id="star_icon"></i>
         {% else %}
           <i class="fa fa-star-o fa-lg" aria-hidden="true" id="star_icon"></i>
         {% endif %}
         <br>

         <span id="js-star-count">{{ subject.points.count }}</span>
      </a>
    </div>

    <div class="body-partition">
      <p class="post-info text-muted">
        <a href="{{ subject.board.get_absolute_url }}"
           title="visit board"
           class="board-link">b/{{ subject.board.slug }}</a> &bull;
        Posted by
        <a href="{% url 'user_profile' subject.author.username %}"
           title="view profile"
           class="profile-link">{{ subject.author.profile.screen_name }}</a>
        <span title="{{ subject.created|date:"D d M Y" }} | {{ subject.created|time:"H:i:s" }}">
           {{ subject.created|naturaltime }}
        </span>
      </p>
      <h5><a href="{{ subject.get_absolute_url }}" class="card-link">{{ subject.title|emoticons }}</a></h5>
      <p>{{ subject.body|urlize }}</p>

      {% if subject.photo %}
      <div class="card-photo-stlying">
        <img src="{{ subject.photo.url }}" width="80%">
      </div>
      {% endif %}

      <div class="card-bottom-area text-muted">
        <a href="{{ subject.get_absolute_url }}"
           title="{{ subject.comments.count }} comments">
           <i class="fa fa-comment fa-md" aria-hidden="true"></i> {{ subject.comments.count }} Comments
        </a> &bull;
        <a href="#" class="share_link" data-clipboard-text="{{ request.get_host }}{{ subject.get_absolute_url }}">
           <i class="fa fa-share fa-md" aria-hidden="true"></i> Share
        </a>
        <div style="float:right;">
          {% ifequal subject.author request.user %}
            <a href="{% url 'edit_subject' subject.slug %}"
               title="edit subject">
               <i class="fa fa-edit fa-lg"></i> Edit</a> &bull;
          {% endifequal %}
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
$(document).ready(function(){
  // Star or unstar a post
  $(document).on("click", "#js-star-subject", function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $star_count = $(this).find('#js-star-count');
    var $star_url = $(this).attr("href");
    var $star_icon = $(this).find('i.fa');
    $.ajax({
      url: $star_url,
      type: 'GET',
      success: function (data) {
        $star_count.text(data.total_points);

        if ($star_icon.hasClass('fa-star-o')) {
          $star_icon.removeClass('fa-star-o').addClass('fa-star');
        }
        else if ($star_icon.hasClass('fa-star')) {
          $star_icon.removeClass('fa-star').addClass('fa-star-o');
        } else {
          console.log('Unexpected error!');
        }
      }
    });
    {% endif %}
    return false;
  });

  // Show tooltip on click for 1 sec
  $('.share_link').on('click', function(e) {
    e.preventDefault();
    var elm = $(this);
    elm.tooltip({
      trigger: 'click',
      placement: 'bottom',
      title: 'Copied permalink!'
    });
    setTimeout(function(){
        elm.tooltip('hide');
    }, 1000);
  });
 
</script>

<script src="{% static 'js/clipboard.min.js' %}"></script>
<script type="text/javascript">
new ClipboardJS('.share_link');
</script>


<style>
#comments_container li a#commenter {
    border-radius: 100px;
    padding: 1px 10px;
    border: 1px solid #d6d6d6;
}
#comments_container li a#commenter:hover {
    border: 1px solid #3f51b5;
}
#comment_form #comment_text {
    background-color: #f8f9fa;
}
#comment_form #comment_text:focus {
    background-color: #fff;
}
</style>

{% if comments %}
<div class="card" style="margin:15px 0px;">
  <div class="card-header">
    Comments
  </div>
  <ul class="list-group list-group-flush" id="comments_container">
    {% for comment in comments %}
    <li class="list-group-item" comment-id="{{comment.id}}">
      <p>{{comment.body|emoticons}}
      <br><a href="{% url 'user_profile' comment.commenter.username %}" title="view profile" id="commenter" class="card-link">{{comment.commenter}}</a> &#8212;
      <span title="{{comment.created|date:"D d M Y"}} | {{comment.created|time:"H:i:s"}}">{{comment.created|naturaltime}}</span>

    </p></li>
    {% endfor %}
  </ul>
</div>
{% else %}
<div class="card" style="margin:15px 0px;">
  <div class="card-header">
    Comments
  </div>
  <ul class="list-group list-group-flush" id="comments_container">
    <div style="padding:15px;" id="no_comments">
      <h6 class="text-center">No comments to display</h6>
    </div>
  </ul>
</div>
{% endif %}