mysite/urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

import boards.views as boards_views
import notifications.views as notifications_views
import search.views as search_views
import subjects.views as subjects_views
import users.views as users_views
from subjects.sitemaps import SubjectSitemap
from messenger.urls import *

sitemaps = {
    'subjects': SubjectSitemap,
}

urlpatterns = [
    

    re_path(r'^home/$',login_required(subjects_views.HomePageView.as_view()), name='home'),
    re_path(r'^$',users_views.user_login,name='login'),
    re_path(r'^s/(?P<board>[-\w]+)/(?P<subject>[-\w]+)/$',
        subjects_views.subject_detail,
        name='subject_detail'),
    re_path(r'^b/$',boards_views.BoardsPageView.as_view(), name='view_all_boards'),
    re_path(r'^b/(?P<board>[-\w]+)/$',
        boards_views.BoardPageView.as_view(),
        name='board'),
    
    re_path(r'^b/(?P<board>[-\w]+)/edit_board_cover/$',
        boards_views.edit_board_cover,
        name='edit_board_cover'),
    re_path(r'^b/(?P<board>[-\w]+)/subscription/$',
        boards_views.subscribe,
        name='subscribe'),
    re_path(r'^b/(?P<subject>[-\w]+)/like/$',
        subjects_views.like_subject,
        name='like'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/subscriptions/$', boards_views.UserSubscriptionListView.as_view(),
        name='user_subscription_list'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/boards/$', boards_views.UserCreatedBoardsPageView.as_view(),
        name='user_created_boards'),
    re_path(r'^new_post/$',subjects_views.new_subject, name='new_subject'),
    re_path(r'^edit_subject/(?P<subject>[-\w]+)/$', subjects_views.edit_subject, name='edit_subject'),
    re_path(r'^new_board/$',boards_views.new_board, name='new_board'),

    # user profiles
    re_path(r'^u/$', users_views.UsersPageView.as_view(), name='view_all_users'),
    re_path(r'^u/following/$', users_views.FollowingPageView.as_view(), name='view_following'),
    re_path(r'^u/followers/$', users_views.FollowersPageView.as_view(), name='view_all_followers'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/$', users_views.UserProfilePageView.as_view(), name='user_profile'),
    re_path(r'^u/follow_user/(?P<user_id>\d+)/$',
        users_views.follow_user,
        name='follow_user'),
    re_path(r'^u/send_message_request/(?P<user_id>\d+)/$',
        users_views.send_message_request,
        name='send_message_request'),
    re_path(r'^u/accept_message_request/(?P<user_id>\d+)/$',
        users_views.accept_message_request,
        name='accept_message_request'),
    re_path(r'^u/friends/all/$', users_views.all_friends, name='all_friends'),
    re_path(r'^u/friends/requests/$', users_views.all_message_requests, name='all_message_requests'),
    re_path(r'^activities/$', notifications_views.ActivitiesPageView.as_view(), name='activities'),
    re_path(r'^activities/check/$', notifications_views.check_activities, name='check_activities'),

    # login / logout urls
    re_path(r'^login/$',users_views.user_login,name='login'),
    re_path(r'^logout/$',users_views.user_logout,
            name='logout'),
    re_path(r'^logout-then-login/$',
            auth_views.logout_then_login,
            name='logout_then_login'),

    # password change re_paths
    re_path(r'^password_change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    re_path(r'^password-change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),


    # user registration
    re_path(r'^signup/$',
        users_views.register_user,
        name='signup'),

    # verify username availability in database via ajax request
    re_path(r'^signup/check_username/$', users_views.check_username, name='check_username'),

    # profile edit
    re_path(r'^profile_edit/$', users_views.profile_edit,
        name='profile_edit'),
    re_path(r'^picture_change/$', users_views.change_picture,
        name='picture_change'),

    # search
    re_path(r'^search/$',search_views.search, name='search'),
    re_path(r'^board_search/(?P<board_slug>[-\w]+)/$',search_views.search, name='board_search'),

    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    
    re_path(r'^messages/', include('messenger.urls')),

    path('', include('pwa.urls'))

]

if True:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

users/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class Profile(models.Model):
    """
    Model that represents a profile.
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile', on_delete=models.CASCADE)
    dp = models.ImageField(upload_to='dps/', blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    followers = models.ManyToManyField(
        User, related_name='following', blank=True
    )
    contact_list = models.ManyToManyField(
        User, related_name='contacters', blank=True
    )
    pending_list = models.ManyToManyField(
        User, related_name='my_pending_requests', blank=True
    )
    member_since = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-member_since', )

    def __str__(self):
        """Unicode representation for a profile model."""
        return self.user.username

    def screen_name(self):
        """Returns screen name."""
        try:
            if self.user.get_full_name():
                return self.user.get_full_name()
            else:
                return self.user.username
        except:  # noqa: E722
            return self.user.username

    def get_picture(self):
        """Returns profile picture url (if any)."""
        default_picture = settings.STATIC_URL + 'img/ditto.jpg'
        if self.dp:
            return self.dp.url
        else:
            return default_picture


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    """
    Signals the Profile about User creation.
    """
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

users/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class SignupForm(forms.ModelForm):
    """
    Form that handles signup data.
    """

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserEditForm(forms.ModelForm):
    """
    Form that handles user data.
    """

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    """
    Form that handles profile data.
    """

    class Meta:
        model = Profile
        fields = ('dob', 'dp')

users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, authenticate, login as auth_login,
    logout as auth_logout,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.views.generic import ListView

import requests

from mysite.decorators import ajax_required
from notifications.models import Notification
from subjects.models import Subject
from utils import check_image_extension

from .forms import ProfileEditForm, SignupForm, UserEditForm
from .models import Profile
from .decorattors import unauthenticated_user

@unauthenticated_user
def register_user(request):
    form_filling = True
    if request.method == 'POST':
        user_form = SignupForm(data=request.POST or None)
        if not user_form.is_valid():
            return render(request, 'registration/register.html', {
                'user_form': user_form, 'form_filling': form_filling
            })
        else:
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            auth = authenticate(
                username=user_form.cleaned_data['username'],
                password=user_form.cleaned_data['password'],
                )
            auth_login(request, auth)
            msg_txt = """
                    <h4 class="alert-heading" >
                        Welcome to Elixio!
                    </h4>
                    <p style="color:#000000;">
                        Thanks for joining our community. Start sharing your ideas by posting
                        <a href="/new_post/" class="alert-link">new subject</a> or just create
                        your own <a href="/new_board/" class="alert-link">new board</a>.
                    </p>
                    <hr>
                    <p class="mb-0" style="color:#000000;">
                        Add your <a href="/profile_edit/" class="alert-link">profile info</a>,
                        so community members know you well.
                    </p>
                """
            messages.success(request, msg_txt)
            return redirect('/')
    else:
        user_form = SignupForm()
    return render(request, 'registration/register.html', {
        'user_form': user_form, 'form_filling': form_filling
    })
    
    
@ajax_required
def check_username(request):
    """
    Ajax call to check username availability.
    """
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)


@login_required
def user_logout(request):
    """
    Logout the current user.
    """
    auth_logout(request)
    return redirect('login')


class UsersPageView(ListView):
    """
    Basic ListView implementation to call the users list.
    """
    model = User
    paginate_by = 20
    template_name = 'users/view_all_users.html'
    context_object_name = 'users'

    def get_queryset(self, **kwargs):
        return User.objects.exclude(username=self.request.user.username)


class FollowersPageView(LoginRequiredMixin, ListView):
    """
    Basic ListView implementation to call the followers list per user.
    """
    model = User
    paginate_by = 20
    template_name = 'users/followers.html'
    context_object_name = 'users'

    def get_queryset(self, **kwargs):
        return self.request.user.profile.followers.all()


class FollowingPageView(LoginRequiredMixin, ListView):
    """
    Basic ListView implementation to call the following list per user.
    """
    model = User
    paginate_by = 20
    template_name = 'users/following.html'
    context_object_name = 'profiles'

    def get_queryset(self, **kwargs):
        return self.request.user.following.all()


@login_required
@ajax_required
def follow_user(request, user_id):
    """
    Ajax call to follow a user.
    """
    user = get_object_or_404(User,
                             id=user_id)
    if request.user in user.profile.followers.all():
        user.profile.followers.remove(request.user)
        text = 'Follow'
    else:
        user.profile.followers.add(request.user)
        Notification.objects.create(
            Actor=request.user,
            Target=user,
            notif_type='follow'
        )
        text = 'Unfollow'
    return HttpResponse(text)


@login_required
def profile_edit(request):
    """
    Handles user profile edit action.
    """
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST)
        if user_form.is_valid():
            user_form.save()
        else:
            user_form = UserEditForm(instance=request.user)

        if profile_form.is_valid():
            profile_form.save()
        else:
            profile_form = ProfileEditForm(instance=request.user.profile)

        msg_txt = """
            <p>Your profile info is successfully saved. <a href="/" class="alert-link">Go to homepage</a></p>
        """

        messages.success(request, msg_txt)
        return redirect('profile_edit')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request, 'users/profile_edit.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


@login_required
def change_picture(request):
    """
    Handles profile picture change action.
    """
    if request.method == 'POST':
        user_dp = request.FILES.get('dp')
        if check_image_extension(user_dp.name):
            profile_form = Profile.objects.get(user=request.user)
            profile_form.dp = user_dp
            profile_form.save()
            msg_txt = """
                <p>Your profile picture is successfully saved. <a href="/" class="alert-link">Go to homepage</a></p>
            """
            messages.success(request, msg_txt)
        else:
            msg_txt = """
                <p>
                    Filetype not supported. Please use .jpg or .png filetypes.
                    <a href="/" class="alert-link">Go to homepage</a>
                </p>
            """
            messages.warning(request, msg_txt)
            return redirect('picture_change')

        return redirect('user_profile', username=request.user.username)
    else:
        profile_form = ProfileEditForm(instance=request.user.profile)
        return render(request, 'users/change_picture.html', {'profile_form': profile_form})


class UserProfilePageView(LoginRequiredMixin, ListView):
    """
    Basic ListView implementation to call the subjects list & profile per user.
    """
    model = Subject
    paginate_by = 15
    template_name = 'users/profile.html'
    context_object_name = 'subjects'

    def get_queryset(self, **kwargs):
        self.user = get_object_or_404(User,
                                      username=self.kwargs['username'])
        return Subject.get_subjects(self.user)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["user"] = self.user
        return context


@login_required
@ajax_required
def send_message_request(request, user_id):
    """
    Ajax call to send a message request.
    """
    receiver = get_object_or_404(User, id=user_id)
    contacter = request.user

    if contacter in receiver.profile.pending_list.all():
        receiver.profile.pending_list.remove(contacter)
        text = 'Send Request'
    else:
        receiver.profile.pending_list.add(contacter)
        Notification.objects.create(Actor=contacter, Target=receiver, notif_type='sent_msg_request')
        text = 'Request Sent'
    return HttpResponse(text)


@login_required
@ajax_required
def accept_message_request(request, user_id):
    """
    Ajax call to accept a message request.
    """
    sender = get_object_or_404(User, id=user_id)
    acceptor = request.user

    if sender in acceptor.profile.pending_list.all():
        acceptor.profile.pending_list.remove(sender)
        acceptor.profile.contact_list.add(sender)
        sender.profile.contact_list.add(acceptor)
        Notification.objects.create(Actor=acceptor, Target=sender, notif_type='confirmed_msg_request')
        text = 'Added to contact list'
    else:
        text = 'Unexpected error!'
    return HttpResponse(text)


@login_required
def all_message_requests(request):
    """
    Displays a message requests list of users.
    """
    message_requests = request.user.profile.pending_list.all()

    paginator = Paginator(message_requests, 20)
    page = request.GET.get('page')
    if paginator.num_pages > 1:
        p = True
    else:
        p = False
    try:
        users = paginator.page(page)

    except PageNotAnInteger:
        users = paginator.page(1)

    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    p_obj = users

    return render(request, 'users/view_all_message_requests.html', {
        'users': users,
        'page': page,
        'p': p,
        'p_obj': p_obj
    })


@login_required
def all_friends(request):
    """
    Displays a friends list of users.
    """
    user_contact_list = request.user.profile.contact_list.all()

users/templates/users/change_picture.html
{% extends "base_home.html" %}
{% block title %}<title>Account Settings | Elixio</title>{% endblock %}

{% block content %}
{% include "includes/page_heading.html" with text="Account Settings" %}

<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'profile_edit' %}">Edit profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'picture_change' %}">Add picture</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'password_change' %}">Change password</a>
  </li>
</ul>

<div class="container" style="text-align:center;">
  <img src="{{request.user.profile.get_picture}}" width="300px" height="300px">
</div>

<form action="{% url 'picture_change' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_dp">Upload a picture</label>
    <input type="file" class="form-control-file" id="id_dp" name="dp" accept="image/*">
  </div>
 <button type="submit" class="btn btn-primary btn-block" id="submit_pic" style="background-color: #ff4500;">Submit</button>

<br></form>
{% endblock %}

users/templates/users/followers.html
{% extends "base_home.html" %}
{% load static %}
{% load boards_tags %}
{% load humanize %}

{% block title %}<title>Followers | Elixio</title>{% endblock %}

{% block content %}
{% include "includes/page_heading.html" with text="Followers" %}
{% if users %}
  {% include "users/includes/partial_user.html" with users=users %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Followers Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">You don't have any followers right now.</p>
    </div>
  </div>
{% endif %}

{% endblock content %}

users/templates/users/following.html
{% extends "base_home.html" %}
{% load static %}
{% load boards_tags %}
{% load humanize %}

{% block title %}<title>Following | Elixio</title>{% endblock %}

{% block content %}
{% include "includes/page_heading.html" with text="Following" %}
{% for profile in profiles %}
<div class="card mb-2" style="background-color: #0e0e0e; border-color:#000000; border-radius: 5px;">
  <div class="card-body p-4" >

    <div class="text-center" style="float:left; width:10%;">
      {% if profile.user.profile.get_picture %}
      <img src="{{ profile.user.profile.get_picture }}" class="rounded" width="50px" height="50px">
      {% endif %}
    </div>

    <div style="float:right; width:90%;">
      <h5 style="font-size:16px;">
        <a href="{% url 'user_profile' profile.user.username %}"
           class="card-link"
           title="{{ profile.user.username }}">{{ profile.screen_name }}</a>
         </h5>
      <p class="text-muted">Member since <span title="{{ profile.member_since|date:"D d M Y" }} | {{ profile.member_since|time:"H:i:s" }}">{{ profile.member_since|naturaltime }}</span></p>
    </div>
  </div>
</div>
{% empty %}
<div class="card p-4 my-4 mx-0" style="background-color: #0e0e0e; border-color: #000000; border-radius: 5px;">
  <h6 class="text-center" style="color: white;">No Following Found</h6>
  <div style="margin:0 auto;">
  <p class="text-muted">You don't have any following right now.</p>
  </div>
</div>
{% endfor %}

{% endblock %}

users/templates/users/profile.html
{% extends "base_home.html" %}
{% load humanize %}

{% block title %}<title>{{user.profile.screen_name}} | Elixio</title>{% endblock %}

{% block content %}

{% if request.user.username == user.username %}
  {% include "includes/page_heading.html" with text="Your Profile" %}
{% else %}
  {% include "includes/page_heading.html" with text=user.profile.screen_name %}
{% endif %}

<style>
#profile_user_links a { border-radius: 100px; padding: 4px 15px; margin:15px; border: 1px solid #d6d6d6; }
#profile_user_links a:hover { border: 1px solid #ff4500; }
</style>

<div class="card" style="width:25%; float:left; border:none;">
  <img class="card-img-top" src="{{ user.profile.get_picture }}">
</div>

<div class="card" style="width:75%; float:right; background-color: #0e0e0e; border-color: #000000; border-radius: 5px;">
  <div class="card-body">
    <h4 class="card-title" style="color: white;" >
    {{ user.profile.screen_name }} &nbsp;
    {% ifequal request.user user %}
    {% else %}
      {% if not request.user in user.profile.contact_list.all %}
        {% if request.user in user.profile.pending_list.all %}
            <a href="{% url 'send_message_request' user.id %}"
               class="btn btn-primary btn-sm"
               id="send_message_request"
               style="margin-right: 10px;"
               title="Request sent to this users">Request Sent</a>
        {% else %}
            <a href="{% url 'send_message_request' user.id %}"
               class="btn btn-outline-primary btn-sm"
               id="send_message_request"
               style="margin-right: 10px;"
               title="Send request to this user to start conversation">Send Request</a>
        {% endif %}
      {% else %}
            <!-- Block User Trigger -->
            <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#blockUserModel">Block</button>

            <!-- Block User Modal -->
            <div class="modal fade" id="blockUserModel" tabindex="-1" role="dialog" aria-labelledby="Block User" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Are you sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <h5>Once you block the user, you can not message him again until he accepts your request.</h5><br>
                    <p>If user is being annoying to you, block him right away.</p>

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Cancel</button>
                 </div>
                </div>
              </div>
            </div>
            <a href="{% url 'messages' user.username %}" class="btn btn-outline-primary btn-sm" id="send_msg" title="Send message to this user" style="margin-right: 10px;">Message</a>
      {% endif %}
    {% endifequal %}

    {% ifequal request.user user %}
    {% else %}
    	{% if request.user in user.profile.followers.all %}
      		<a href="{% url 'follow_user' user.id %}" class="btn btn-primary btn-sm" id="follow_user">Unfollow</a>
    	{% else %}
        	<a href="{% url 'follow_user' user.id %}" class="btn btn-outline-primary btn-sm" id="follow_user">Follow</a>
    	{% endif %}
    {% endifequal %}

    </h4>
    <p class="card-text"><strong>{{user.inspected_boards.count}}</strong> boards created.</p>
    <p class="card-text"><strong>{{user.posted_subjects.count}}</strong> subjects posted.</p>
    <p class="card-text"><strong>{{user.subscribed_boards.count}}</strong> boards subscribed.</p>
    <p class="card-text">Member since <span title="{{ user.profile.member_since|date:"D d M Y" }} | {{ user.profile.member_since|time:"H:i:s" }}">{{ user.profile.member_since|date:"M d Y" }}</span></p>
    <br>

    
    <p id="profile_user_links" style="text-align:center;"><a href="{% url 'user_subscription_list' user.username %}" class="card-link">View subscription list</a>
    {% ifequal request.user user %}
    <a href="{% url 'profile_edit' %}" class="card-link">Edit profile</a><br><br>
    <a href="{% url 'view_all_followers' %}" class="card-link">Followers</a>
    <a href="{% url 'view_following' %}" class="card-link">Following</a><br><br>
    <a href="{% url 'all_message_requests' %}" class="card-link">Message requests</a>
    <a href="{% url 'all_friends' %}" class="card-link">Contact list</a></p>
    {% endifequal %}
  </div>
</div>

<div style="clear:both;"></div>

{% if request.user.username == user.username %}
  {% include "includes/page_heading.html" with text="Your Recent Posts" %}
{% else %}
  {% include "includes/page_heading.html" with text="Recent Posts" %}
{% endif %}

{% if subjects %}
  {% include "includes/partial_subject.html" with subjects=subjects %}
{% else %}
<div class="card p-4 my-4 mx-0">
  <h6 class="text-center">No Posts Found</h6>
  <div style="margin:0 auto;">
  <p class="text-muted">You don't have any posts right now.</p>
  </div>
</div>
{% endif %}


<script type="text/javascript">
// Send Request
$(document).ready(function(){
  $("a#send_message_request").on("click", function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $add_btn = $(this);
    var $add_url = $(this).attr("href");
    $.ajax({
      url: $add_url,
      type: 'GET',
      success: function (data) {
        $add_btn.text(data);

        if ($add_btn.hasClass('btn-outline-primary')) {
          $add_btn.removeClass('btn-outline-primary').addClass('btn-primary');
        }
        else if ($add_btn.hasClass('btn-primary')) {
          $add_btn.removeClass('btn-primary').addClass('btn-outline-primary');
        }
        else {
          console.log('Unexpected error!');
        }
      }
    });
    {% endif %}
    return false;
  });
});
</script>

<script>
// Follow user
$(document).ready(function(){
    $("a#follow_user").on("click", function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $follow_btn = $(this);
    var $follow_url = $(this).attr("href");
    $.ajax({
      url: $follow_url,
      type: 'GET',
      success: function (data) {
        $follow_btn.text(data);

        if ($follow_btn.hasClass('btn-outline-primary')) {
          $follow_btn.removeClass('btn-outline-primary').addClass('btn-primary');
        }
        else if ($follow_btn.hasClass('btn-primary')) {
          $follow_btn.removeClass('btn-primary').addClass('btn-outline-primary');
        }
        else {
          console.log('Unexpected error!');
        }
      }
    });
    {% endif %}
    return false;
  });
});
</script>
{% endblock %}

users/templates/users/profile_edit.html
{% extends "base_home.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block title %}<title>Account Settings | Elixio</title>{% endblock %}

{% block content %}
{% include "includes/page_heading.html" with text="Account Settings" %}

<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'profile_edit' %}">Edit profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'picture_change' %}">Add picture</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'password_change' %}">Change password</a>
  </li>
</ul>

<form action="{% url 'profile_edit' %}" method="post">
  {% csrf_token %}
  {{ user_form|crispy }}
  <div class="form-group">
    <label for="id_dob">Date of Birth</label>
    {% render_field profile_form.dob class="form-control" %}
  </div>
  <button type="submit" class="btn btn-success btn-block" style="background-color: #ff4500;">Save</button>
<br>
</form>
{% endblock %}

users/templates/users/view_all_contacts.html
{% extends "base_home.html" %}
{}


{% block title %}<title>Contact List | Elixio</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Contact List" %}
{% if users %}
  {% include "users/includes/partial_user.html" with users=users %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Contacts Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">You don't have any contact right now.</p>
    </div>
  </div>
{% endif %}

{% endblock content %}

users/templates/users/view_all_users.html
{% extends "base_home.html" %}
{% load static %}
{% load boards_tags %}
{% load humanize %}

{% block title %}<title>Users | Elixio</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Users" %}
{% if users %}
  {% include "users/includes/partial_user.html" with users=users %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Users Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">There are no users right now.</p>
    </div>
  </div>
{% endif %}

{% endblock content %}